### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arshizx** [GuckTubeYT/GTPSLauncherCSharp#1]
@GuckTubeYT How To Fix This
![dc2de9f31ee5760a9d012cd14f90ed0e](https://user-images.githubusercontent.com/48289599/76002439-92491f00-5f41-11ea-90e5-4ea748fe0020.png)

**Comment by arshizx** [comment]
@GuckTubeYT

**Comment by GuckTubeYT** [comment]
hmmmm... wait ok

**Comment by GuckTubeYT** [comment]
done bro

**Comment by GuckTubeYT** [comment]
thanks for remember me

**Comment by GuckTubeYT** [comment]
dont forget to re download again

**Comment by arshizx** [comment]
ok ty bro

**Comment by GuckTubeYT** [comment]
> ok ty bro

Youre welcome
